export { useDashboard } from './useDashboard'
export { useEvents } from './useEvents'
export { useTasks } from './useTasks'
export { usePlanning } from './usePlanning'
export { useEvidences } from './useEvidences'
export { useClasses } from './useClasses'
export { useHistory } from './useHistory'