export { eventsService } from './events.service'
export { tasksService } from './tasks.service'
export { planningService } from './planning.service'
export { evidencesService } from './evidences.service'
export { classesService } from './classes.service'